### ISSUE TITLE
Personal checklist

### ISSUE THREAD

**Issue by JDoddsNAIT** [JDoddsNAIT/Unity-Scripts#1]
## Follow transform

- [x] Add square deadzone
- [x] Add help attribute
- [x] Add formatting attributes

## Add Gizmo

- [x] Add help attribute
- [x] Add formatting attributes

## Rigidbody magnet

- [ ] Remove `FindGameObjectsWithTag` from `Update()`
- [ ] Add help attribute
- [ ] Add formatting attributes

## Rigidbody magnet 2D

- [ ] Remove `FindGameObjectsWithTag` from `Update()`
- [ ] Add help attribute
- [ ] Add formatting attributes
